import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { SpeedInsights } from "@vercel/speed-insights/next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="ltr" lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider enableSystem={true} attribute="class">
          {children}
          <SpeedInsights />
        </ThemeProvider>
      </body>
    </html>
  );
}
